# Generated by Django 5.1.3 on 2025-03-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_friendship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
