# Generated by Django 5.1.3 on 2025-05-03 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'routine', 'day', 'activity_name', 'date')},
            },
        ),
    ]
