# Generated by Django 5.1.3 on 2025-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_routineactivitycompletion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routineactivitycompletion',
            unique_together={('user', 'routine', 'day', 'activity_name')},
        ),
        migrations.AddField(
            model_name='routineactivitycompletion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='routineactivitycompletion',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='routineactivitycompletion',
            name='date',
        ),
    ]
